version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Expo Metro Bundler port
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - ./.docker/expo:/root/.expo # Persist expo configuration and login
    env_file:
      - .env
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - WATCH_DOCUMENT_CHANGES=true
    stdin_open: true # Keep stdin open for interactivity
    tty: true # Allocate a pseudo-TTY

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
