export const EXERCISE_REPOSITORY_TOKEN = Symbol('EXERCISE_REPOSITORY');
export const TAG_REPOSITORY_TOKEN = Symbol('TAG_REPOSITORY');
export const PHASE_EXERCISE_REPOSITORY_TOKEN = Symbol(
  'PHASE_EXERCISE_REPOSITORY',
);
export const FAVORITE_EXERCISE_REPOSITORY_TOKEN = Symbol(
  'FAVORITE_EXERCISE_REPOSITORY',
);
export const EXERCISE_RATING_REPOSITORY_TOKEN = Symbol(
  'EXERCISE_RATING_REPOSITORY',
);
