export const CYCLE_REPOSITORY_TOKEN = 'CYCLE_REPOSITORY';
export const CYCLE_PROFILE_CONFIG_REPOSITORY_TOKEN =
  'CYCLE_PROFILE_CONFIG_REPOSITORY';
export const PHASE_REPOSITORY_TOKEN = 'PHASE_REPOSITORY';
export const SYMPTOM_LOG_REPOSITORY_TOKEN = 'SYMPTOM_LOG_REPOSITORY';
