export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY';
export const REFRESH_TOKEN_REPOSITORY_TOKEN = 'REFRESH_TOKEN_REPOSITORY';
export const USER_SETTINGS_REPOSITORY_TOKEN = 'USER_SETTINGS_REPOSITORY';
